rabbitcarrot: Disabled
illusionerspawning: 15%
killerrabbitspawning: 1%
egglay: Enabled
jebcolor: Enabled
lefthanded: 30%
shulkercolor: Enabled
snifferbrain: Disabled
irongolemanger: Enabled
jebspawning: 2%
locator_assets: Enabled
immunezombie: 10%
brownmoospawning: 10%
creeperfuse: Enabled
skeletonhorsetrap: Enabled
mobs_on_locator_bar: Enabled
babymountspawning: 2%
need_sky: Enabled
