jebspawning_initial: '2'
rabbitcarrot: Disabled
brownmoospawning_initial: '10'
illusionerspawning: 15%
killerrabbitspawning: 1%
irongolemanger_initial: 'false'
egglay: Enabled
need_sky_initial: 'false'
rabbitcarrot_initial: 'true'
illusionerspawning_initial: '15'
jebcolor: Enabled
locator_assets_initial: 'false'
lefthanded: 30%
creeperfuse_initial: 'false'
lefthanded_initial: '30'
shulkercolor: Enabled
snifferbrain: Disabled
mobs_on_locator_bar_initial: 'false'
irongolemanger: Enabled
snifferbrain_initial: 'true'
jebspawning: 2%
command_template: function mob_manager:dialog/command_template/misc {mobs_on_locator_bar:$(mobs_on_locator_bar),lefthanded:$(lefthanded),shulkercolor:$(shulkercolor),rabbitcarrot:$(rabbitcarrot),locator_assets:$(locator_assets),snifferbrain:$(snifferbrain),immunezombie:$(immunezombie),creeperfuse:$(creeperfuse),skeletonhorsetrap:$(skeletonhorsetrap),irongolemanger:$(irongolemanger),brownmoospawning:$(brownmoospawning),illusionerspawning:$(illusionerspawning),babymountspawning:$(babymountspawning),killerrabbitspawning:$(killerrabbitspawning),jebcolor:$(jebcolor),jebspawning:$(jebspawning),egglay:$(egglay),need_sky:$(need_sky)}
locator_assets: Enabled
immunezombie: 10%
brownmoospawning: 10%
immunezombie_initial: '10'
creeperfuse: Enabled
killerrabbitspawning_initial: '1'
skeletonhorsetrap: Enabled
shulkercolor_initial: 'false'
mobs_on_locator_bar: Enabled
skeletonhorsetrap_initial: 'false'
egglay_initial: 'false'
jebcolor_initial: 'false'
babymountspawning_initial: '2'
babymountspawning: 2%
need_sky: Enabled
