Chance For Ender Dragon To Drop A Dragon Egg: 10%
Chance For Creaking To Drop Resin: 80%
Chance For Stray To Drop Ice: 25%
Chance For Goat To Drop Leather: 40%
Chance For Shulker To Drop Additional Shulker Shell: 25%
Chance For Allay To Drop Amethyst Shard: 90%
Chance For Elder Guardian To Drop Heart Of The Ocean: 75%
Chance For Villager To Drop Emerald: 40%
Chance For Wandering Trader To Drop Lead: '1'
Chance For Piglin To Drop Gold: 20%
Chance For Bee To Drop Honeycomb: 5%
Chance For Ender Dragon To Drop Elytra: 50%
Chance For Wither Skeleton To Drop Additional Skull: '1'
Chance For Fox To Drop Sweet Berries: 60%
Chance For Bat To Drop Phantom Membrane: 33%
Chance For Piglin Brute To Drop Gold Block: 50%
Chance For Husk To Drop Sand: 25%
