dragonegg: 10%
creakingresin: 80%
strayice: 25%
goatleather: 40%
shulkerdrop: 25%
allayshard: 90%
elderguardianseaheart: 75%
villageremerald: 40%
traderlead: '1'
piglingold: 20%
beehoneycomb: 5%
dragonelytra: 50%
witherskulldrop: '1'
foxsweetberries: 60%
batmembrane: 33%
piglinbrutegoldblock: 50%
husksand: 25%
