Mainhand:
  Chance Of Item Being Dropped (Only Applies When Not Vanilla): '0'
  Chance Of Item Being Enchanted: 40%
  Apply Random Damage To Item: Enabled
  Chance Of Entity Being Equipped With Custom Item: 10%
  Entity Tag List Used: mob_manager:valid_for_equipment
  Loot Table Used For Custom Equipment Item: mob_manager:entity/equipment/mainhand
Offhand:
  Chance Of Item Being Dropped (Only Applies When Not Vanilla): '0'
  Chance Of Item Being Enchanted: 40%
  Apply Random Damage To Item: Enabled
  Chance Of Entity Being Equipped With Custom Item: 5%
  Entity Tag List Used: mob_manager:valid_for_equipment
  Loot Table Used For Custom Equipment Item: mob_manager:entity/equipment/offhand
Head:
  Chance Of Item Being Dropped (Only Applies When Not Vanilla): '0'
  trim_material: diamond
  trim_pattern: raiser
  Chance Of Item Being Enchanted: 40%
  Apply Random Damage To Item: Enabled
  Chance Of Entity Being Equipped With Custom Item: 15%
  Leather Equipment Can Have Random Colors: '1630197'
  Entity Tag List Used: mob_manager:valid_for_equipment
  Loot Table Used For Custom Equipment Item: mob_manager:entity/equipment/head
Misc:
  Chance Of Entity Wearing A Random Mob Head: 15%
  Equipment Can Be Trimmed: Enabled
  Shields Have Random Banners: Enabled
  Mainhand Item For Vex: air
  Leather Equipment Can Have Random Colors: Enabled
  Chance For Entity Wearing A Random Mob Head: 5%
Feet:
  Chance Of Item Being Dropped (Only Applies When Not Vanilla): '0'
  trim_material: copper
  trim_pattern: bolt
  Chance Of Item Being Enchanted: 40%
  Apply Random Damage To Item: Enabled
  Chance Of Entity Being Equipped With Custom Item: 25%
  Leather Equipment Can Have Random Colors: '16641964'
  Entity Tag List Used: mob_manager:valid_for_equipment
  Loot Table Used For Custom Equipment Item: mob_manager:entity/equipment/feet
Legs:
  Chance Of Item Being Dropped (Only Applies When Not Vanilla): '0'
  trim_material: redstone
  trim_pattern: dune
  Chance Of Item Being Enchanted: 40%
  Apply Random Damage To Item: Enabled
  Chance Of Entity Being Equipped With Custom Item: 25%
  Leather Equipment Can Have Random Colors: '5263538'
  Entity Tag List Used: mob_manager:valid_for_equipment
  Loot Table Used For Custom Equipment Item: mob_manager:entity/equipment/legs
Chest:
  Chance Of Item Being Dropped (Only Applies When Not Vanilla): '0'
  trim_material: emerald
  trim_pattern: flow
  Chance Of Item Being Enchanted: 40%
  Apply Random Damage To Item: Enabled
  Chance Of Entity Being Equipped With Custom Item: 25%
  Leather Equipment Can Have Random Colors: '8483931'
  Entity Tag List Used: mob_manager:valid_for_equipment
  Loot Table Used For Custom Equipment Item: mob_manager:entity/equipment/chest
