shulkerdrop_initial: '25'
batmembrane_initial: '33'
villageremerald_initial: '40'
traderlead_initial: '100'
dragonegg: 10%
creakingresin: 80%
strayice: 25%
goatleather_initial: '40'
goatleather: 40%
shulkerdrop: 25%
strayice_initial: '25'
allayshard: 90%
elderguardianseaheart: 75%
husksand_initial: '25'
dragonegg_initial: '10'
villageremerald: 40%
traderlead: '1'
piglingold: 20%
beehoneycomb_initial: '5'
beehoneycomb: 5%
dragonelytra: 50%
command_template: function mob_manager:dialog/command_template/mob_drops {witherskulldrop:$(witherskulldrop),creakingresin:$(creakingresin),traderlead:$(traderlead),foxsweetberries:$(foxsweetberries),piglinbrutegoldblock:$(piglinbrutegoldblock),piglingold:$(piglingold),allayshard:$(allayshard),goatleather:$(goatleather),strayice:$(strayice),elderguardianseaheart:$(elderguardianseaheart),villageremerald:$(villageremerald),beehoneycomb:$(beehoneycomb),husksand:$(husksand),batmembrane:$(batmembrane),shulkerdrop:$(shulkerdrop),dragonegg:$(dragonegg),dragonelytra:$(dragonelytra)}
elderguardianseaheart_initial: '75'
piglingold_initial: '20'
dragonelytra_initial: '50'
witherskulldrop: '1'
witherskulldrop_initial: '100'
foxsweetberries_initial: '60'
foxsweetberries: 60%
batmembrane: 33%
allayshard_initial: '90'
piglinbrutegoldblock: 50%
creakingresin_initial: '80'
husksand: 25%
piglinbrutegoldblock_initial: '50'
