mainhand:
  dropchance: '0'
  enchantment: 40%
  slot: mainhand
  rngdmg: Enabled
  capslot: Mainhand
  equipchance: 10%
  validmobs: mob_manager:valid_for_equipment
  equiploottable: mob_manager:entity/equipment/mainhand
offhand:
  dropchance: '0'
  enchantment: 40%
  slot: offhand
  rngdmg: Enabled
  capslot: Offhand
  equipchance: 5%
  validmobs: mob_manager:valid_for_equipment
  equiploottable: mob_manager:entity/equipment/offhand
head:
  dropchance: '0'
  trim_material: diamond
  trim_pattern: raiser
  enchantment: 40%
  slot: head
  rngdmg: Enabled
  capslot: Head
  equipchance: 15%
  leathercolor: '1630197'
  validmobs: mob_manager:valid_for_equipment
  equiploottable: mob_manager:entity/equipment/head
misc:
  mobheads: 15%
  trim: Enabled
  bannershield: Enabled
  vex_equip: air
  leathercolor: Enabled
  playerheads: 5%
feet:
  dropchance: '0'
  trim_material: copper
  trim_pattern: bolt
  enchantment: 40%
  slot: feet
  rngdmg: Enabled
  capslot: Feet
  equipchance: 25%
  leathercolor: '16641964'
  validmobs: mob_manager:valid_for_equipment
  equiploottable: mob_manager:entity/equipment/feet
legs:
  dropchance: '0'
  trim_material: redstone
  trim_pattern: dune
  enchantment: 40%
  slot: legs
  rngdmg: Enabled
  capslot: Legs
  equipchance: 25%
  leathercolor: '5263538'
  validmobs: mob_manager:valid_for_equipment
  equiploottable: mob_manager:entity/equipment/legs
chest:
  dropchance: '0'
  trim_material: emerald
  trim_pattern: flow
  enchantment: 40%
  slot: chest
  rngdmg: Enabled
  capslot: Chest
  equipchance: 25%
  leathercolor: '8483931'
  validmobs: mob_manager:valid_for_equipment
  equiploottable: mob_manager:entity/equipment/chest
