rare:
  type: rare
  bodyicon: lime_bundle
  loottable: mob_manager:entity/rarity_mob/filled_bundle
  particles: Enabled
  customname: Enabled
  color: 58CD78
  spawnchance: 3%
  last_name: Skyforge
  particles_initial: 'false'
  cap_type: Rare
  health: '50'
  customname_initial: 'false'
  spawnchance_initial: '3'
  first_name: Thorne
  spawntime: '60'
  validmobs: mob_manager:valid_for_rarity
  command_template: ',customname:$(customname),particles:$(particles),spawntime:$(spawntime),spawnchance:$(spawnchance),health:$(health),validmobs:''$(validmobs)'',loottable:''$(loottable)''}'
legendary:
  type: legendary
  bodyicon: yellow_bundle
  loottable: mob_manager:entity/rarity_mob/enchanted_book
  particles: Enabled
  customname: Enabled
  color: F8D40C
  spawnchance: 2%
  last_name: Villagercraft
  particles_initial: 'false'
  cap_type: Legendary
  health: '75'
  customname_initial: 'false'
  spawnchance_initial: '2'
  first_name: Kieran
  spawntime: '60'
  validmobs: mob_manager:valid_for_rarity
  command_template: ',customname:$(customname),particles:$(particles),spawntime:$(spawntime),spawnchance:$(spawnchance),health:$(health),validmobs:''$(validmobs)'',loottable:''$(loottable)''}'
mythic:
  type: mythic
  bodyicon: purple_bundle
  loottable: mob_manager:entity/rarity_mob/enchanted_equipment
  particles: Enabled
  customname: Enabled
  color: B277D7
  spawnchance: 1%
  last_name: Archerheart
  particles_initial: 'false'
  cap_type: Mythic
  health: '100'
  customname_initial: 'false'
  spawnchance_initial: '1'
  first_name: Thaddeus
  spawntime: '60'
  validmobs: mob_manager:valid_for_rarity
  command_template: ',customname:$(customname),particles:$(particles),spawntime:$(spawntime),spawnchance:$(spawnchance),health:$(health),validmobs:''$(validmobs)'',loottable:''$(loottable)''}'
common:
  type: common
  bodyicon: white_bundle
  loottable: mob_manager:entity/rarity_mob/valuables
  particles: Enabled
  customname: Enabled
  color: E8E8E8
  spawnchance: 5%
  last_name: Wolfcraft
  particles_initial: 'false'
  cap_type: Common
  health: '30'
  customname_initial: 'false'
  spawnchance_initial: '5'
  first_name: Eowyn
  spawntime: '60'
  validmobs: mob_manager:valid_for_rarity
  command_template: ',customname:$(customname),particles:$(particles),spawntime:$(spawntime),spawnchance:$(spawnchance),health:$(health),validmobs:''$(validmobs)'',loottable:''$(loottable)''}'
