Rare:
  Type: rare
  Entity Particles: Enabled
  Loot Table Used On Death: mob_manager:entity/rarity_mob/filled_bundle
  Entity Has Custom Name: Enabled
  Color: 58CD78
  Chance Of Becoming A Rarity Mob Of This Type: 3%
  Health (%): '50'
  Time In Seconds Before Entity Can Become A Rarity Mob Of This Type: '60'
  Entity Tag List Used: mob_manager:valid_for_rarity
Legendary:
  Type: legendary
  Entity Particles: Enabled
  Loot Table Used On Death: mob_manager:entity/rarity_mob/enchanted_book
  Entity Has Custom Name: Enabled
  Color: F8D40C
  Chance Of Becoming A Rarity Mob Of This Type: 2%
  Health (%): '75'
  Time In Seconds Before Entity Can Become A Rarity Mob Of This Type: '60'
  Entity Tag List Used: mob_manager:valid_for_rarity
Mythic:
  Type: mythic
  Entity Particles: Enabled
  Loot Table Used On Death: mob_manager:entity/rarity_mob/enchanted_equipment
  Entity Has Custom Name: Enabled
  Color: B277D7
  Chance Of Becoming A Rarity Mob Of This Type: 1%
  Health (%): '100'
  Time In Seconds Before Entity Can Become A Rarity Mob Of This Type: '60'
  Entity Tag List Used: mob_manager:valid_for_rarity
Common:
  Type: common
  Entity Particles: Enabled
  Loot Table Used On Death: mob_manager:entity/rarity_mob/valuables
  Entity Has Custom Name: Enabled
  Color: E8E8E8
  Chance Of Becoming A Rarity Mob Of This Type: 5%
  Health (%): '30'
  Time In Seconds Before Entity Can Become A Rarity Mob Of This Type: '60'
  Entity Tag List Used: mob_manager:valid_for_rarity
