rare:
  type: rare
  loottable: mob_manager:entity/rarity_mob/filled_bundle
  particles: Enabled
  customname: Enabled
  color: 58CD78
  spawnchance: 3%
  last_name: Skyforge
  cap_type: Rare
  health: '50'
  first_name: Thorne
  spawntime: '60'
  validmobs: mob_manager:valid_for_rarity
legendary:
  type: legendary
  loottable: mob_manager:entity/rarity_mob/enchanted_book
  particles: Enabled
  customname: Enabled
  color: F8D40C
  spawnchance: 2%
  last_name: Villagercraft
  cap_type: Legendary
  health: '75'
  first_name: Kieran
  spawntime: '60'
  validmobs: mob_manager:valid_for_rarity
mythic:
  type: mythic
  loottable: mob_manager:entity/rarity_mob/enchanted_equipment
  particles: Enabled
  customname: Enabled
  color: B277D7
  spawnchance: 1%
  last_name: Archerheart
  cap_type: Mythic
  health: '100'
  first_name: Thaddeus
  spawntime: '60'
  validmobs: mob_manager:valid_for_rarity
common:
  type: common
  loottable: mob_manager:entity/rarity_mob/valuables
  particles: Enabled
  customname: Enabled
  color: E8E8E8
  spawnchance: 5%
  last_name: Wolfcraft
  cap_type: Common
  health: '30'
  first_name: Eowyn
  spawntime: '60'
  validmobs: mob_manager:valid_for_rarity
