pet: 1%
villagecenter_healing: daytime
customname: Enabled
breeddiversity: Enabled
villagename_rename: Enabled
villagename: Enabled
restock: Disabled
validmobs: mob_manager:valid_for_village_healing
villagename_msg: title
village_heal_distance: '16'
locator_range: '196'
villager_follow: Disabled
locator_color: 664c28
gossip: Enabled
talking: actionbar
