treasurebook: Enabled
spawnmsg: actionbar
customname: Enabled
treasurebookpayitem: minecraft:emerald
spawnglow: Enabled
treasurebookpayamount: '12'
miniblock: Enabled
miniblockpayitem: minecraft:emerald
plushie: Enabled
plushiepayamount: '6'
plushiepayitem: minecraft:emerald
miniblockpayamount: '2'
