type: copper_golem
bodyicon: copper_golem_spawn_egg
scale_min: '80'
move_speed: '100'
drown_initial: 'false'
burn_initial: 'false'
silent_initial: 'true'
drown: Enabled
allow_mob: Enabled
allow_mob_initial: 'false'
breed: Enabled
follow_range: '100'
silent: Disabled
command_template: ',tempt_range:$(tempt_range),mobhead:$(mobhead),allow_mob:$(allow_mob),locator_color:''$(locator_color)'',locator_range:$(locator_range),pickup:$(pickup),scale_min:$(scale_min),scale_max:$(scale_max),health:$(health),follow_range:$(follow_range),safe_fall:$(safe_fall),move_speed:$(move_speed),burn:$(burn),silent:$(silent),drown:$(drown),breed:$(breed)}'
pickup_initial: 'false'
mobhead_initial: '25'
tempt_range: '100'
locator_color: 64e764
pickup: Enabled
locator_range: '0'
breed_initial: 'false'
health: '100'
burn: Enabled
safe_fall: '100'
mobhead: 25%
scale_max: '100'
