type: drowned
scale_min: '90'
move_speed: '100'
allow_mob: Enabled
drown: Enabled
breed: Enabled
follow_range: '100'
silent: Disabled
attck_dmg: '100'
tempt_range: '100'
locator_color: ade6e6
pickup: Enabled
locator_range: '12'
health: '100'
burn: Enabled
safe_fall: '100'
mobhead: 25%
scale_max: '110'
