Type: happy_ghast
Min Entity Size (%): '90'
Movement Speed (%): '100'
Entity Can Drown: Enabled
Entity Spawning: Enabled
Entity Can Breed: Enabled
Follow Range (%): '100'
Entity Is Silent By Default: Disabled
Tempt Range (%): '100'
Locator Bar Color (Hex): 64e764
Entity Can Pickup Loot: Enabled
Locator Bar Range in Blocks: '8'
Health (%): '100'
Entity Can Burn: Enabled
Safe Fall Distance (%): '100'
Chance Of Entity Dropping Its Head: 25%
Max Entity Size (%): '110'
