type: villager
scale_min: '90'
move_speed: '100'
drown: Enabled
allow_mob: Enabled
breed: Enabled
follow_range: '100'
silent: Disabled
tempt_range: '100'
locator_color: 64e764
pickup: Enabled
locator_range: '8'
health: '100'
burn: Enabled
safe_fall: '100'
mobhead: 25%
scale_max: '110'
