attck_dmg: '100'
scale_min: '90'
drown: Enabled
move_speed: '100'
locator_range: '16'
pickup: Enabled
locator_color: 8b0000
allow_mob: Enabled
health: '100'
burn: Enabled
safe_fall: '100'
follow_range: '100'
silent: Disabled
mobhead: 25%
scale_max: '110'
type: zombie
