Type: zombified_piglin
Min Entity Size (%): '90'
Movement Speed (%): '100'
Entity Can Drown: Enabled
Entity Spawning: Enabled
Entity Can Breed: Enabled
Follow Range (%): '100'
Entity Is Silent By Default: Disabled
Attack Damage (%): '100'
Tempt Range (%): '100'
Locator Bar Range in Blocks: '12'
Entity Can Pickup Loot: Enabled
Locator Bar Color (Hex): ade6e6
Health (%): '100'
Entity Can Burn: Enabled
Safe Fall Distance (%): '100'
Chance Of Entity Dropping Its Head: 25%
Max Entity Size (%): '110'
