type: zombie_nautilus
bodyicon: zombie_nautilus_spawn_egg
scale_min: '90'
move_speed: '100'
drown_initial: '0'
burn_initial: '0'
silent_initial: '1'
allow_mob: Enabled
drown: Enabled
allow_mob_initial: '0'
breed: Enabled
follow_range: '100'
silent: Disabled
command_template: ',tempt_range:$(tempt_range),mobhead:$(mobhead),allow_mob:$(allow_mob),locator_color:''$(locator_color)'',locator_range:$(locator_range),pickup:$(pickup),attck_dmg:$(attck_dmg),scale_min:$(scale_min),scale_max:$(scale_max),health:$(health),follow_range:$(follow_range),safe_fall:$(safe_fall),move_speed:$(move_speed),burn:$(burn),silent:$(silent),drown:$(drown),breed:$(breed)}'
attck_dmg: '100'
pickup_initial: '0'
mobhead_initial: '25'
tempt_range: '100'
locator_color: ade6e6
pickup: Enabled
locator_range: '12'
breed_initial: '0'
health: '100'
burn: Enabled
safe_fall: '100'
mobhead: 25%
scale_max: '110'
