minecraft:advance_weather: 1
minecraft:max_entity_cramming: 24
minecraft:fall_damage: 1
minecraft:command_block_output: 1
minecraft:spawn_wardens: 1
minecraft:respawn_radius: 0
minecraft:max_command_sequence_length: 65536
minecraft:drowning_damage: 1
minecraft:immediate_respawn: 0
minecraft:tnt_explosion_drop_decay: 0
minecraft:player_movement_check: 0
minecraft:natural_health_regeneration: 1
minecraft:spectators_generate_chunks: 1
minecraft:players_nether_portal_creative_delay: 0
minecraft:fire_damage: 1
minecraft:advance_time: 1
minecraft:keep_inventory: 1
minecraft:command_blocks_work: 1
minecraft:log_admin_commands: 0
minecraft:block_drops: 1
minecraft:limited_crafting: 0
minecraft:elytra_movement_check: 0
minecraft:global_sound_events: 0
minecraft:lava_source_conversion: 1
minecraft:spread_vines: 1
minecraft:players_nether_portal_default_delay: 0
minecraft:players_sleeping_percentage: 51
minecraft:entity_drops: 1
minecraft:spawn_phantoms: 0
minecraft:spawn_mobs: 1
minecraft:freeze_damage: 1
minecraft:forgive_dead_players: 1
minecraft:mob_drops: 1
minecraft:max_command_forks: 65536
minecraft:show_advancement_messages: 0
minecraft:water_source_conversion: 1
minecraft:allow_entering_nether_using_portals: 1
minecraft:show_death_messages: 0
minecraft:spawn_patrols: 1
minecraft:block_explosion_drop_decay: 1
minecraft:send_command_feedback: 0
minecraft:max_block_modifications: 32768
minecraft:mob_griefing: 1
minecraft:pvp: 1
minecraft:spawn_monsters: 1
minecraft:locator_bar: 1
minecraft:fire_spread_radius_around_player: 0
minecraft:random_tick_speed: 3
minecraft:ender_pearls_vanish_on_death: 0
minecraft:spawner_blocks_work: 1
minecraft:spawn_wandering_traders: 1
minecraft:mob_explosion_drop_decay: 1
minecraft:tnt_explodes: 1
minecraft:max_snow_accumulation_height: 4
minecraft:projectiles_can_break_blocks: 1
minecraft:universal_anger: 0
minecraft:reduced_debug_info: 0
minecraft:raids: 1
