minecraft:advance_weather: Enabled
minecraft:max_entity_cramming: '24'
minecraft:fall_damage: Enabled
minecraft:command_block_output: Enabled
minecraft:spawn_wardens: Enabled
minecraft:respawn_radius: Disabled
minecraft:max_command_sequence_length: '65536'
minecraft:drowning_damage: Enabled
minecraft:immediate_respawn: Disabled
minecraft:tnt_explosion_drop_decay: Disabled
minecraft:player_movement_check: Disabled
minecraft:natural_health_regeneration: Enabled
minecraft:keep_inventory: Enabled
minecraft:players_nether_portal_creative_delay: Disabled
minecraft:fire_damage: Enabled
minecraft:advance_time: Enabled
minecraft:command_blocks_work: Enabled
minecraft:spectators_generate_chunks: Enabled
minecraft:log_admin_commands: Disabled
minecraft:block_drops: Enabled
minecraft:limited_crafting: Disabled
minecraft:elytra_movement_check: Disabled
minecraft:global_sound_events: Disabled
minecraft:spread_vines: Enabled
minecraft:lava_source_conversion: Enabled
minecraft:players_nether_portal_default_delay: Disabled
minecraft:players_sleeping_percentage: '51'
minecraft:entity_drops: Enabled
minecraft:spawn_phantoms: Disabled
minecraft:spawn_mobs: Enabled
minecraft:freeze_damage: Enabled
minecraft:forgive_dead_players: Enabled
minecraft:mob_drops: Enabled
minecraft:water_source_conversion: Enabled
minecraft:show_advancement_messages: Disabled
minecraft:max_command_forks: '65536'
minecraft:allow_entering_nether_using_portals: Enabled
minecraft:show_death_messages: Disabled
minecraft:spawn_patrols: Enabled
minecraft:block_explosion_drop_decay: Enabled
minecraft:mob_griefing: Enabled
minecraft:max_block_modifications: '32768'
minecraft:send_command_feedback: Disabled
minecraft:pvp: Enabled
minecraft:spawn_monsters: Enabled
minecraft:locator_bar: Enabled
minecraft:fire_spread_radius_around_player: Disabled
minecraft:random_tick_speed: '3'
minecraft:ender_pearls_vanish_on_death: Disabled
minecraft:spawner_blocks_work: Enabled
minecraft:spawn_wandering_traders: Enabled
minecraft:mob_explosion_drop_decay: Enabled
minecraft:tnt_explodes: Enabled
minecraft:max_snow_accumulation_height: '4'
minecraft:projectiles_can_break_blocks: Enabled
minecraft:universal_anger: Disabled
minecraft:reduced_debug_info: Disabled
minecraft:raids: Enabled
