Max Claims Per Player: '-1'
Enable PVP In Claims: Enabled
Allow Damaging Unnamed Hostile Mobs: Enabled
Allow Damaging Named Hostile Mobs: Enabled
Claim Protects Full World Height: Disabled
Claim Area Height Multiplier: '1'
Claim Area Is Bound To Chunks: Disabled
Allow Claim Overlapping If Same Owner: Enabled
Protect Against Hostile Explosions Triggered By Trusted Players: Enabled
Enabled Claim Augments:
  Withering Seal: Disabled
  Explosion Controller: Enabled
  Spirit Grave: Disabled
  PVP Arena: Enabled
  Heaven Wings: Disabled
  Chaos Zone: Disabled
  Village Core: Enabled
  Greeter: Enabled
  Force Field: Disabled
  Ender Binding: Disabled
  Angelic Aura: Disabled
Allowed Blocks For Interactions Regardless Of Trust:
- minecraft:oak_button
- minecraft:ender_chest
- minecraft:vault
- minecraft:crafting_table
- minecraft:grindstone
- minecraft:stonecutter
- minecraft:enchanting_table
- minecraft:smithing_table
- minecraft:loom
- minecraft:cartography_table
- minecraft:green_bed
- minecraft:red_bed
- minecraft:white_bed
- minecraft:gray_bed
- minecraft:light_gray_bed
- minecraft:black_bed
- minecraft:brown_bed
- minecraft:orange_bed
- minecraft:yellow_bed
- minecraft:lime_bed
- minecraft:cyan_bed
- minecraft:light_blue_bed
- minecraft:blue_bed
- minecraft:purple_bed
- minecraft:magenta_bed
- minecraft:pink_bed
Allowed Entities For Interactions Regardless Of Trust:
- minecraft:interaction
- minecraft:villager
Claim Anchor Radius:
  Makeshift: '10'
  Reinforced: '25'
  Glistening: '50'
  Crystal: '75'
  Emerdic: '125'
  Withered: '200'
