equip_dmg: enabled
grave_status: enabled
exp_loss_amount: 0.30000001192092896
grave_duration: 30
player_head_drop_chance: 0.10000000149011612
exp_loss: enabled
equip_dmg_amount: 0.1
non_droppable_tag_list: keepinv:non_droppable_items
player_head_drop: enabled
grave_type: random
