equip_dmg: Enabled
grave_status: Enabled
exp_loss_amount: 30%
grave_duration: '30'
player_head_drop_chance: 10%
exp_loss: Enabled
equip_dmg_amount: 10%
non_droppable_tag_list: keepinv:non_droppable_items
player_head_drop: Enabled
grave_type: random
