Time Format For HUD: '24'
Min Y Height For RTP: '90'
RTP Radius (in Blocks): '3000'
spawn_z: '185'
Events:
  fishing:
    chance: 10%
    loot_table: eden:gameplay/events/fishing
    max_amount: '48'
  consuming:
    chance: 6%
    loot_table: eden:gameplay/events/consuming
    max_amount: '96'
  breeding:
    chance: 8%
    loot_table: eden:gameplay/events/breeding
    max_amount: '24'
  misc:
    thursday: disabled
    monday: enabled
    sunday: disabled
    friday: enabled
    saturday: disabled
    tuesday: disabled
    wednesday: enabled
  killing:
    chance: 9%
    loot_table: eden:gameplay/events/killing
    max_amount: '96'
  brewing:
    chance: 7%
    loot_table: eden:gameplay/events/brewing
    max_amount: '48'
RTP Type: player
rtp_height_max: '120'
Action Costs:
  Horse Info: '0'
  Death/Grave Coordinates: '0'
  Transfer Enchantments: '30'
  Broadcast Coordinates: '0'
  RTP: '5'
  Sit: '0'
  TP Home: '0'
  Set Home: '0'
  TP To Spawn: '0'
  Equip Item As Hat: '0'
  Share Stats: '3'
  Villager Info: '0'
Action Cooldowns (Seconds):
  TP To Spawn: '60'
  RTP: '300'
  TP Home: '20'
