time_format: '24'
spawn_y: '72'
rtp_height_min: '90'
rtp_radius: '3000'
horse_info_cost: '0'
death_coords_cost: '0'
spawn_z: '185'
events:
  fishing:
    type: fishing
    chance: 10%
    loot_table: eden:gameplay/events/fishing
    max_amount: '48'
  consuming:
    type: consuming
    chance: 6%
    loot_table: eden:gameplay/events/consuming
    max_amount: '96'
  breeding:
    type: breeding
    chance: 8%
    loot_table: eden:gameplay/events/breeding
    max_amount: '24'
  misc:
    thursday: Disabled
    monday: Enabled
    event_msg: title
    sunday: Disabled
    friday: Enabled
    saturday: Disabled
    tuesday: Disabled
    wednesday: Enabled
  killing:
    type: killing
    chance: 9%
    loot_table: eden:gameplay/events/killing
    max_amount: '96'
  brewing:
    type: brewing
    chance: 7%
    loot_table: eden:gameplay/events/brewing
    max_amount: '48'
tp_spawn_cooldown: '60'
transfer_enchantments_cost: '30'
rtp_type: player
send_coords_cost: '0'
rtp_cooldown: '300'
rtp_cost: '5'
spawn_dimension: minecraft:overworld
sit_cost: '0'
tp_home_cost: '0'
spawn_x: '26'
set_home_cost: '0'
tp_spawn_cost: '0'
equip_hat_cost: '0'
share_stats_cost: '3'
rtp_height_max: '120'
tp_home_cooldown: '20'
time_hud_style: '1'
villager_info_cost: '0'
