Time Format For HUD: '24'
spawn_y: '72'
Min Y Height For RTP: '90'
RTP Radius (in Blocks): '3000'
spawn_z: '185'
Events:
  fishing:
    type: fishing
    chance: 10%
    loot_table: eden:gameplay/events/fishing
    max_amount: '48'
  consuming:
    type: consuming
    chance: 6%
    loot_table: eden:gameplay/events/consuming
    max_amount: '96'
  breeding:
    type: breeding
    chance: 8%
    loot_table: eden:gameplay/events/breeding
    max_amount: '24'
  misc:
    thursday: Disabled
    monday: Enabled
    event_msg: title
    sunday: Disabled
    friday: Enabled
    saturday: Disabled
    tuesday: Disabled
    wednesday: Enabled
  killing:
    type: killing
    chance: 9%
    loot_table: eden:gameplay/events/killing
    max_amount: '96'
  brewing:
    type: brewing
    chance: 7%
    loot_table: eden:gameplay/events/brewing
    max_amount: '48'
RTP Type: player
spawn_dimension: minecraft:overworld
spawn_x: '26'
Max Y Height For RTP: '120'
time_hud_style: '1'
Action Costs:
  horse_info_cost: '0'
  death_coords_cost: '0'
  transfer_enchantments_cost: '30'
  send_coords_cost: '0'
  rtp_cost: '5'
  sit_cost: '0'
  tp_home_cost: '0'
  set_home_cost: '0'
  tp_spawn_cost: '0'
  equip_hat_cost: '0'
  share_stats_cost: '3'
  villager_info_cost: '0'
Action Cooldowns (Seconds):
  tp_spawn_cooldown: '60'
  rtp_cooldown: '300'
  tp_home_cooldown: '20'
