gamerules:
  fall_damage: 'true'
  drowning_damage: 'true'
  tnt_explodes: 'true'
  mob_griefing: 'true'
  fire_damage: 'true'
  mob_drops: 'true'
  players_nether_portal_creative_delay: 0
  block_explosion_drop_decay: 'true'
  universal_anger: 'false'
  allow_entering_nether_using_portals: 'true'
  advance_time: 'true'
  player_movement_check: 'false'
  tnt_explosion_drop_decay: 'false'
  log_admin_commands: 'true'
  spawn_wandering_traders: 'true'
  raids: 'true'
  spawn_mobs: 'true'
  spawn_phantoms: 'false'
  lava_source_conversion: 'true'
  locator_bar: 'true'
  command_blocks_work: 'true'
  mob_explosion_drop_decay: 'true'
  difficulty_normal: 'true'
  limited_crafting: 'false'
  immediate_respawn: 'false'
  global_sound_events: 'false'
  spawn_monsters: 'true'
  respawn_radius: 0
  reduced_debug_info: 'false'
  players_sleeping_percentage: 51
  difficulty_easy: 'false'
  spawn_wardens: 'true'
  command_block_output: 'true'
  max_block_modifications: 32768
  max_entity_cramming: 24
  difficulty_hard: 'false'
  ender_pearls_vanish_on_death: 'false'
  water_source_conversion: 'true'
  max_command_forks: 65536
  fire_spread_radius_around_player: 0
  elytra_movement_check: 'false'
  max_snow_accumulation_height: 4
  pvp: 'true'
  keep_inventory: 'true'
  spectators_generate_chunks: 'true'
  block_drops: 'true'
  natural_health_regeneration: 'true'
  forgive_dead_players: 'true'
  random_tick_speed: 3
  max_command_sequence_length: 65536
  send_command_feedback: 'false'
  advance_weather: 'true'
  projectiles_can_break_blocks: 'true'
  spawner_blocks_work: 'true'
  spawn_patrols: 'true'
  players_nether_portal_default_delay: 0
  spread_vines: 'true'
  difficulty_peaceful: 'false'
  entity_drops: 'true'
  show_advancement_messages: 'false'
  freeze_damage: 'true'
datapack_settings:
  dialog:
  - action:
      type: minecraft:run_command
      command: function minecraft:fabled_roots
    label: Fabled Roots
  - action:
      type: minecraft:run_command
      command: function minecraft:kattersstructures
    label: Katters Structures
  - action:
      type: minecraft:run_command
      command: function minecraft:mob_manager
    label: Nice Mob Manager
  - action:
      type: minecraft:run_command
      command: function minecraft:nice_actions
    label: Nice Actions
  - action:
      type: minecraft:run_command
      command: function minecraft:keep_inventory
    label: Nice Keep Inventory
  - action:
      type: minecraft:run_command
      command: function minecraft:warping_wonders
    label: Warping Wonders
modify_mannequin:
  below_name: ''
  name: ''
  profile: Docm77
  scale: 100
