portal_horn:
  breaking_chance: 0.0
  mob_teleport: enabled
  exp_cost: 5
  active: enabled
clock:
  breaking_chance: 0.5
  mob_teleport: enabled
  exp_cost: 5
  active: disabled
compass:
  breaking_chance: 0.0
  mob_teleport: enabled
  exp_cost: 5
  active: disabled
recovery_compass:
  breaking_chance: 1.0
  mob_teleport: enabled
  exp_cost: 5
  active: disabled
waypoint_hub:
  mob_teleport: enabled
  player_limit: 32
  exp_cost: 0
  active: enabled
  min_distance: 64
